go mod tidy check for dpm (#232)

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -50,6 +50,14 @@ jobs:
       - uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5.6.0
         with:
           go-version: '1.23.5'
+      - name: Check
+        run: |
+            go mod tidy
+            git diff --exit-code --color go.mod go.sum || {
+              echo "::error::Please run 'go mod tidy'"
+              exit 1
+            }
+        shell: bash
       - run: go build -o target/ ./cmd/...
         shell: bash
       - name: Run Go tests and generate in json format
